/**
 * PipelineProgress — multi-level timeline of an agent turn's progress.
 *
 * Layout:
 *   - Header with summary headline + actions (Show timeline / Expand all).
 *   - Optional "Design Plan" highlight card pulled from the planning step, so
 *     the user sees the agent's commitment without clicking.
 *   - Optional "Vision verifier" highlight card pulled from the latest
 *     critique step, so the score and issues are visible without clicking.
 *   - Vertical timeline grouped by iteration. The latest step pulses while a
 *     live run is in progress, and the live planner/code-gen reasoning streams
 *     inline under whichever step opted into a reasoning channel.
 */

import { useEffect, useMemo, useRef, useState } from 'react';
import { useChatStore } from '../stores';
import type { PipelineStep } from '../types';

interface PipelineProgressProps {
  steps: PipelineStep[];
  isLive?: boolean;
}

const STAGE_META: Record<string, { icon: string; label: string; tone: 'neutral' | 'good' | 'bad' | 'warn' }> = {
  planning:     { icon: '◴', label: 'Planning',     tone: 'neutral' },
  researching:  { icon: '⌕', label: 'Researching',  tone: 'neutral' },
  generating:   { icon: '✦', label: 'Generating',   tone: 'neutral' },
  executing:    { icon: '▶', label: 'Executing',    tone: 'neutral' },
  tessellating: { icon: '◆', label: 'Tessellating', tone: 'neutral' },
  rendering:    { icon: '◐', label: 'Rendering',    tone: 'neutral' },
  critiquing:   { icon: '◉', label: 'Verifying',    tone: 'neutral' },
  validating:   { icon: '✓', label: 'Validating',   tone: 'good'    },
  repairing:    { icon: '↻', label: 'Repairing',    tone: 'warn'    },
  failed:       { icon: '✕', label: 'Failed',       tone: 'bad'     },
};

const SUB_STAGE_LABELS: Record<string, string> = {
  context: 'Context',
  strategy: 'Strategy',
  recipes: 'Recipes',
  example_bank: 'Examples',
  plan_drafting: 'Drafting',
  plan_repair: 'Plan repair',
  plan_repair_partial: 'Plan repair · partial',
  plan_repair_ok: 'Plan repair · ok',
  plan_ready: 'Plan ready',
  research_skipped: 'Skipped',
  search: 'Searching',
  results: 'Results',
  no_results: 'No results',
  error: 'Error',
};

function stageMeta(stage: string) {
  return STAGE_META[stage] ?? { icon: '·', label: stage, tone: 'neutral' as const };
}

function joinNicely(items: string[]): string {
  if (items.length === 1) return items[0];
  if (items.length === 2) return `${items[0]} and ${items[1]}`;
  return `${items.slice(0, -1).join(', ')}, and ${items.slice(-1)[0]}`;
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60_000) return `${(ms / 1000).toFixed(1)}s`;
  const m = Math.floor(ms / 60_000);
  const s = Math.floor((ms % 60_000) / 1000);
  return `${m}m ${s}s`;
}

function formatClockTime(iso: string): string {
  try {
    const d = new Date(iso);
    if (isNaN(d.getTime())) return '';
    const hh = String(d.getHours()).padStart(2, '0');
    const mm = String(d.getMinutes()).padStart(2, '0');
    const ss = String(d.getSeconds()).padStart(2, '0');
    return `${hh}:${mm}:${ss}`;
  } catch {
    return '';
  }
}

function formatOffset(ms: number): string {
  if (ms <= 0) return '+0.0s';
  return `+${formatDuration(ms)}`;
}

/**
 * Hook that returns Date.now() refreshed at `intervalMs` while `enabled` is
 * true. Used to drive live timers for the current running step and turn.
 */
function useTicker(enabled: boolean, intervalMs = 200): number {
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => {
    if (!enabled) return;
    const id = window.setInterval(() => setNow(Date.now()), intervalMs);
    return () => window.clearInterval(id);
  }, [enabled, intervalMs]);
  return now;
}

/**
 * Small "LLM" pill rendered in front of a text block that comes verbatim from
 * a language-model output (planner, code generator, vision verifier, etc.).
 * The point is to make it obvious which words in the timeline are model
 * output vs. orchestrator-authored copy. Hover-tooltip explains the source.
 */
function LLMBadge({ source }: { source?: string }) {
  return (
    <span className="llm-badge" title={source ? `From the ${source} LLM` : 'Generated by an LLM'}>LLM</span>
  );
}

/**
 * Decide whether the orchestrator's `rationale` field for this step is
 * pure LLM output. Most rationales are agent-authored explanations of why a
 * step exists. Two are LLM-decided: the "search" sub-stage's rationale is the
 * planner's `research_reasoning`, and "research_skipped" reuses that same
 * reasoning.
 */
function rationaleSource(step: PipelineStep): 'agent' | 'planner' {
  const sub = step.data?.sub_stage;
  if (step.stage === 'researching' && sub === 'search') return 'planner';
  if (step.stage === 'planning' && sub === 'research_skipped') return 'planner';
  return 'agent';
}

/**
 * `outcome` is LLM-sourced for the plan-ready step (plan.summary), the
 * post-critique step (vision verifier's repair_prompt), and the "skipped
 * vision" fallback (verifier's raw message).
 */
function outcomeSource(step: PipelineStep): 'agent' | 'planner' | 'vision' {
  if (step.stage === 'planning' && step.data?.sub_stage === 'plan_ready') return 'planner';
  if (step.stage === 'critiquing' && step.data?.vision_score != null) return 'vision';
  if (step.stage === 'critiquing' && (step.data?.skipped as string[] | undefined)?.includes('vision repair')) return 'vision';
  return 'agent';
}

/**
 * Detect whether a step has substantive expandable content. Casual `data`
 * objects (like a lone iteration tag) don't count.
 */
function hasMeaningfulDetails(step: PipelineStep): boolean {
  if (step.details && step.details.trim()) return true;
  const d = step.data;
  if (!d) return false;
  const keys = Object.keys(d).filter((k) => !['iteration', 'in_progress', 'reasoning_channel', 'sub_stage', 'model_id'].includes(k));
  for (const k of keys) {
    const v = (d as Record<string, unknown>)[k];
    if (v == null) continue;
    if (typeof v === 'string' && v.trim() === '') continue;
    if (Array.isArray(v) && v.length === 0) continue;
    return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// Highlight cards (Design plan, Vision critique)
// ---------------------------------------------------------------------------

interface PlanArtifactProps {
  data: PipelineStep['data'];
}

function DesignPlanCard({ data }: PlanArtifactProps) {
  if (!data) return null;
  const summary = (data.summary || data.plan_summary) as string | undefined;
  const dims = data.overall_dimensions_mm as Record<string, number> | undefined;
  const components = Array.isArray(data.components) ? (data.components as Array<Record<string, unknown>>) : null;
  const keyFeatures = Array.isArray(data.key_features) ? (data.key_features as string[]) : null;
  const assumptions = Array.isArray(data.assumptions) ? (data.assumptions as string[]) : null;
  const risks = Array.isArray(data.risks) ? (data.risks as string[]) : null;
  const parameters = (data.parameters && typeof data.parameters === 'object')
    ? (data.parameters as Record<string, unknown>) : null;

  const dimText = dims
    ? Object.entries(dims).map(([k, v]) => `${k}: ${v} mm`).join(' · ')
    : null;

  return (
    <div className="plan-card">
      <div className="plan-card-header">
        <span className="plan-card-icon" aria-hidden="true">◴</span>
        <span className="plan-card-title">Design plan</span>
        <LLMBadge source="planner" />
        {dimText && <span className="plan-card-dims">{dimText}</span>}
      </div>
      {summary && (
        <div className="plan-card-summary">
          <LLMBadge source="planner" />
          <span>{summary}</span>
        </div>
      )}

      <div className="plan-card-grid">
        {components && components.length > 0 && (
          <div className="plan-card-section">
            <div className="plan-card-section-title">Components ({components.length})</div>
            <ul className="plan-card-list">
              {components.map((c, i) => {
                const name = String(c.name ?? `part ${i + 1}`);
                const desc = typeof c.description === 'string' ? c.description : '';
                const primitive = typeof c.primitive === 'string' ? c.primitive : null;
                const operation = typeof c.operation === 'string' ? c.operation : null;
                const dims = (c.dimensions && typeof c.dimensions === 'object')
                  ? (c.dimensions as Record<string, unknown>) : null;
                const dimsList = dims
                  ? Object.entries(dims).map(([k, v]) => `${k}=${v}`).join(', ')
                  : '';
                return (
                  <li key={i}>
                    <div>
                      <span className="plan-comp-name">{name}</span>
                      {operation && <span className="plan-comp-op"> · {operation}</span>}
                      {primitive && <span className="plan-comp-meta"> · {primitive}</span>}
                      {dimsList && <span className="plan-comp-meta"> ({dimsList})</span>}
                    </div>
                    {desc && <div className="plan-comp-desc">{desc}</div>}
                  </li>
                );
              })}
            </ul>
          </div>
        )}
        {keyFeatures && keyFeatures.length > 0 && (
          <div className="plan-card-section">
            <div className="plan-card-section-title">Key features the result must show</div>
            <ul className="plan-card-list">
              {keyFeatures.map((f, i) => <li key={i}>{f}</li>)}
            </ul>
          </div>
        )}
        {parameters && Object.keys(parameters).length > 0 && (
          <div className="plan-card-section">
            <div className="plan-card-section-title">Parameters</div>
            <ul className="plan-card-list plan-card-list-compact">
              {Object.entries(parameters).map(([k, v]) => (
                <li key={k}><code>{k}</code> = <code>{String(v)}</code></li>
              ))}
            </ul>
          </div>
        )}
        {assumptions && assumptions.length > 0 && (
          <div className="plan-card-section">
            <div className="plan-card-section-title">Assumptions</div>
            <ul className="plan-card-list">
              {assumptions.map((a, i) => <li key={i}>{a}</li>)}
            </ul>
          </div>
        )}
        {risks && risks.length > 0 && (
          <div className="plan-card-section">
            <div className="plan-card-section-title">Risks</div>
            <ul className="plan-card-list">
              {risks.map((r, i) => <li key={i}>{r}</li>)}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
}

interface VisionIssue {
  severity: 'error' | 'warning' | 'info';
  issue_type: string;
  description: string;
  location_hint?: string;
}

function VisionCritiqueCard({ data }: PlanArtifactProps) {
  if (!data) return null;
  const score = typeof data.vision_score === 'number' ? data.vision_score : null;
  const matches = typeof data.matches_intent === 'boolean' ? data.matches_intent : null;
  const issues = Array.isArray(data.vision_issues) ? (data.vision_issues as VisionIssue[]) : [];
  if (score == null && !issues.length) return null;

  const scoreClass = score == null ? '' : score >= 0.8 ? 'good' : score >= 0.65 ? 'warn' : 'bad';

  return (
    <div className="critique-card">
      <div className="critique-card-header">
        <span className="critique-card-icon" aria-hidden="true">◉</span>
        <span className="critique-card-title">Vision verifier</span>
        <LLMBadge source="vision" />
        {score != null && (
          <span className={`critique-card-score ${scoreClass}`}>{score.toFixed(2)}</span>
        )}
        {matches != null && (
          <span className={`critique-card-intent ${matches ? 'good' : 'bad'}`}>
            {matches ? '✓ matches intent' : '✗ intent mismatch'}
          </span>
        )}
      </div>
      {issues.length > 0 && (
        <ul className="critique-card-issues">
          {issues.map((it, i) => (
            <li key={i} className={`critique-issue critique-issue-${it.severity}`}>
              <span className="critique-issue-sev">{it.severity}</span>
              <div>
                <div className="critique-issue-line">
                  <span className="critique-issue-type">{it.issue_type}</span>
                  {it.location_hint && <span className="critique-issue-loc"> · {it.location_hint}</span>}
                </div>
                <div className="critique-issue-desc">{it.description}</div>
              </div>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Individual step row
// ---------------------------------------------------------------------------

interface PipelineStepRowProps {
  step: PipelineStep;
  nextStep: PipelineStep | undefined;
  turnStartMs: number | null;
  nowMs: number;
  isLast: boolean;
  isExpanded: boolean;
  isActive: boolean;
  reasoningText?: string;
  onToggle: () => void;
}

function PipelineStepRow({
  step,
  nextStep,
  turnStartMs,
  nowMs,
  isLast,
  isExpanded,
  isActive,
  reasoningText,
  onToggle,
}: PipelineStepRowProps) {
  const meta = stageMeta(step.stage);
  const data = step.data || {};
  const subStageLabel = typeof data.sub_stage === 'string' ? SUB_STAGE_LABELS[data.sub_stage] ?? data.sub_stage : null;

  const rationale = typeof data.rationale === 'string' ? data.rationale : (typeof data.why === 'string' ? data.why : null);
  const outcome = typeof data.outcome === 'string' ? data.outcome : null;
  const usedInputs = Array.isArray(data.used) ? data.used : null;
  const skipped = Array.isArray(data.skipped) ? data.skipped : null;
  const errorExcerpt = typeof data.error_excerpt === 'string' ? data.error_excerpt
    : typeof data.error === 'string' ? data.error : null;
  const feedback = typeof data.feedback === 'string' ? data.feedback : null;
  const missingFeatures = Array.isArray(data.missing_features) ? (data.missing_features as string[]) : null;
  const missingNegative = Array.isArray(data.missing_negative_space) ? (data.missing_negative_space as string[]) : null;
  const researchResults = Array.isArray(data.research_results) ? (data.research_results as Array<Record<string, string>>) : null;
  const visionIssues = Array.isArray(data.vision_issues) ? (data.vision_issues as VisionIssue[]) : null;
  const recipes = Array.isArray(data.recipes) ? (data.recipes as Array<Record<string, unknown>>) : null;

  // The headline is the message. Long content lives in `details` (multiline
  // OK — rendered with pre-wrap) and in the structured `data` fields.
  const headline = step.message || meta.label;

  // Timestamps:
  //   - startedAt: when this step began
  //   - duration of THIS step = next step's start − this step's start
  //   - live duration (running…) = now − this step's start, shown only for
  //     the currently active (live) step.
  const startedAtMs = step.timestamp ? new Date(step.timestamp).getTime() : null;
  const nextStartMs = nextStep && nextStep.timestamp ? new Date(nextStep.timestamp).getTime() : null;
  const isRunning = isActive && !nextStep;

  let durationLabel: string | null = null;
  if (isRunning && startedAtMs != null) {
    const elapsed = Math.max(0, nowMs - startedAtMs);
    durationLabel = `running ${formatDuration(elapsed)}`;
  } else if (startedAtMs != null && nextStartMs != null) {
    const took = Math.max(0, nextStartMs - startedAtMs);
    // Drop noisy <50ms gaps (cheap synchronous emissions) so the timeline
    // doesn't get peppered with "0ms" durations.
    if (took >= 50) durationLabel = formatDuration(took);
  }

  // Start-time chip: absolute clock if no turn anchor yet, otherwise a
  // relative offset from the start of the turn. Compact and easy to scan.
  let startLabel: string | null = null;
  if (startedAtMs != null) {
    if (turnStartMs != null && startedAtMs >= turnStartMs) {
      startLabel = formatOffset(startedAtMs - turnStartMs);
    } else {
      startLabel = formatClockTime(step.timestamp);
    }
  }
  const startTitle = step.timestamp ? formatClockTime(step.timestamp) : '';

  const hasDetails = hasMeaningfulDetails(step);

  return (
    <div className={`pipeline-step pipeline-step-tone-${meta.tone}${isActive ? ' pipeline-step-active' : ''}`}>
      <div className="pipeline-step-marker">
        <div className={`pipeline-step-icon${isRunning ? ' pipeline-step-icon-running' : ''}`} title={meta.label}>
          {meta.icon}
        </div>
        {!isLast && <div className="pipeline-step-line" />}
      </div>

      <div className="pipeline-step-content">
        <button
          type="button"
          className="pipeline-step-headline"
          onClick={hasDetails ? onToggle : undefined}
          aria-expanded={isExpanded}
          disabled={!hasDetails}
        >
          <span className="pipeline-step-stage">{meta.label}</span>
          {subStageLabel && <span className="pipeline-step-substage">{subStageLabel}</span>}
          <span className="pipeline-step-message">{headline}</span>
          {startLabel && (
            <span className="pipeline-step-start" title={startTitle}>{startLabel}</span>
          )}
          {durationLabel && (
            <span className={`pipeline-step-duration${isRunning ? ' pipeline-step-duration-running' : ''}`}>
              {durationLabel}
            </span>
          )}
          {hasDetails && (
            <span className="pipeline-step-chevron" aria-hidden="true">{isExpanded ? '▾' : '▸'}</span>
          )}
        </button>

        {/* While the step is the live current one, show a larger ticking
            timer below the headline as well, so the user gets a clear
            "actively running for N seconds" signal even if the headline is
            already long. */}
        {isRunning && startedAtMs != null && (
          <div className="pipeline-step-live-timer" aria-live="polite">
            <span className="pipeline-step-live-dot" aria-hidden="true" />
            running for <strong>{formatDuration(Math.max(0, nowMs - startedAtMs))}</strong>
          </div>
        )}

        {/* Live reasoning stream: shown under whichever step opted into a
            channel, so the user can read what the model is thinking right now. */}
        {reasoningText && isRunning && (
          <div className="pipeline-step-reasoning">
            <div className="pipeline-step-reasoning-label">
              <LLMBadge source={step.stage === 'generating' ? 'code generator' : 'planner'} />
              <span>streaming reasoning</span>
            </div>
            <div className="pipeline-step-reasoning-body">{reasoningText}</div>
          </div>
        )}

        {isExpanded && hasDetails && (
          <div className="pipeline-step-body">
            {step.details && step.details.trim() && (
              <div className="pipeline-step-details">{step.details}</div>
            )}

            {rationale && (
              <p className="pipeline-step-rationale">
                {rationaleSource(step) === 'planner' && <LLMBadge source="planner" />}
                <span>{rationale}</span>
              </p>
            )}

            {outcome && (() => {
              const src = outcomeSource(step);
              return (
                <p className="pipeline-step-outcome">
                  {src !== 'agent' && <LLMBadge source={src} />}
                  <span>{outcome}</span>
                </p>
              );
            })()}

            {(usedInputs && usedInputs.length > 0) && (
              <p className="pipeline-step-used">Used: {joinNicely(usedInputs)}</p>
            )}
            {(skipped && skipped.length > 0) && (
              <p className="pipeline-step-skipped">Skipped: {joinNicely(skipped)}</p>
            )}

            {errorExcerpt && (
              <pre className="pipeline-step-error">{errorExcerpt}</pre>
            )}

            {(missingFeatures && missingFeatures.length > 0) && (
              <div className="pipeline-step-missing">
                <div className="pipeline-step-section-label">Missing required features</div>
                <ul>{missingFeatures.map((f, i) => <li key={i}>{f}</li>)}</ul>
              </div>
            )}
            {(missingNegative && missingNegative.length > 0) && (
              <div className="pipeline-step-missing">
                <div className="pipeline-step-section-label">Missing negative-space features</div>
                <ul>{missingNegative.map((f, i) => <li key={i}>{f}</li>)}</ul>
              </div>
            )}
            {feedback && (
              <details className="pipeline-step-feedback">
                <summary>Full feedback</summary>
                <pre>{feedback}</pre>
              </details>
            )}

            {researchResults && researchResults.length > 0 && (
              <div className="pipeline-step-research">
                <div className="pipeline-step-section-label">Sources</div>
                <ul className="pipeline-step-research-list">
                  {researchResults.map((r, i) => {
                    let host = '';
                    try { host = r.url ? new URL(r.url).hostname : ''; } catch { /* ignore */ }
                    return (
                      <li key={i}>
                        <a href={r.url} target="_blank" rel="noreferrer">
                          {r.title || host || r.url}
                        </a>
                        {host && <span className="pipeline-step-research-host"> · {host}</span>}
                        {r.snippet && <div className="pipeline-step-research-snippet">{r.snippet}</div>}
                      </li>
                    );
                  })}
                </ul>
              </div>
            )}

            {recipes && recipes.length > 0 && (
              <div className="pipeline-step-recipes">
                <div className="pipeline-step-section-label">Recipe patterns</div>
                {recipes.map((r, i) => {
                  const required = Array.isArray(r.required_features) ? (r.required_features as string[]) : [];
                  const negative = Array.isArray(r.negative_space_features) ? (r.negative_space_features as string[]) : [];
                  return (
                    <div key={i} className="pipeline-recipe">
                      <div className="pipeline-recipe-title">{String(r.title ?? r.recipe_id)}</div>
                      {required.length > 0 && (
                        <div className="pipeline-recipe-subsection">
                          <span className="pipeline-recipe-label">required:</span>
                          <ul>{required.map((f, j) => <li key={j}>{f}</li>)}</ul>
                        </div>
                      )}
                      {negative.length > 0 && (
                        <div className="pipeline-recipe-subsection">
                          <span className="pipeline-recipe-label">negative-space:</span>
                          <ul>{negative.map((f, j) => <li key={j}>{f}</li>)}</ul>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            )}

            {visionIssues && visionIssues.length > 0 && (
              <div className="pipeline-step-vision-issues">
                <div className="pipeline-step-section-label">
                  <LLMBadge source="vision" />
                  <span>Vision findings</span>
                </div>
                <ul>
                  {visionIssues.map((it, i) => (
                    <li key={i} className={`critique-issue-${it.severity}`}>
                      <span className="critique-issue-sev">{it.severity}</span> {it.issue_type}
                      {it.location_hint && <span className="critique-issue-loc"> · {it.location_hint}</span>}
                      <div>{it.description}</div>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Iteration grouping helpers
// ---------------------------------------------------------------------------

interface IterationGroup {
  iteration: number | null; // null = pre-iteration setup (planning/research)
  startIndex: number;
  steps: PipelineStep[];
}

function groupByIteration(steps: PipelineStep[]): IterationGroup[] {
  const groups: IterationGroup[] = [];
  steps.forEach((step, i) => {
    const it = typeof step.data?.iteration === 'number' ? (step.data.iteration as number) : null;
    const last = groups[groups.length - 1];
    if (!last || last.iteration !== it) {
      groups.push({ iteration: it, startIndex: i, steps: [step] });
    } else {
      last.steps.push(step);
    }
  });
  return groups;
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export default function PipelineProgress({ steps, isLive = false }: PipelineProgressProps) {
  const [showTimeline, setShowTimeline] = useState(isLive);
  const [expanded, setExpanded] = useState<Set<number>>(() => new Set());
  const lastSeenRef = useRef<number>(0);

  // Pull streaming reasoning from the chat store (live runs only). It's the
  // accumulated text from `reasoning_chunk` WebSocket events and is shown
  // under whichever step opted into a reasoning channel.
  const streamingReasoning = useChatStore((s) => s.streamingReasoning);

  // Auto-expand the latest step during a live run.
  useEffect(() => {
    if (!isLive) return;
    if (steps.length > lastSeenRef.current) {
      setExpanded((prev) => {
        const next = new Set(prev);
        next.add(steps.length - 1);
        return next;
      });
      lastSeenRef.current = steps.length;
    }
  }, [steps.length, isLive]);

  // Pull out highlight artifacts (plan + most recent critique) so we can
  // surface them above the timeline.
  const planStep = useMemo(() => {
    // Prefer a step that already carries `plan_ready` sub_stage, else the
    // most recent planning step with components in it.
    for (let i = steps.length - 1; i >= 0; i--) {
      const s = steps[i];
      if (s.stage !== 'planning') continue;
      if (s.data?.sub_stage === 'plan_ready') return s;
      if (Array.isArray(s.data?.components) && (s.data!.components as unknown[]).length > 0) return s;
    }
    return null;
  }, [steps]);

  const critiqueStep = useMemo(() => {
    for (let i = steps.length - 1; i >= 0; i--) {
      const s = steps[i];
      if (s.stage === 'critiquing' && (s.data?.vision_score != null || Array.isArray(s.data?.vision_issues))) {
        return s;
      }
    }
    return null;
  }, [steps]);

  const headline = useMemo(() => {
    if (steps.length === 0) return null;
    const latest = steps[steps.length - 1];
    const meta = stageMeta(latest.stage);
    if (isLive) return `${meta.icon} ${meta.label} — ${latest.message}`;
    const repairs = steps.filter((s) => s.stage === 'repairing').length;
    if (repairs > 0) return `Completed in ${steps.length} steps · ${repairs} repair${repairs === 1 ? '' : 's'}`;
    return `Completed in ${steps.length} steps`;
  }, [steps, isLive]);

  // Turn-level timing.
  //   - turnStartMs: ms epoch of the first step in this turn.
  //   - nowMs: live clock that updates every ~200ms while the run is live.
  //   - turnElapsedMs: how long the turn has run (or took, once finished).
  const nowMs = useTicker(isLive, 200);
  const turnStartMs = useMemo(() => {
    if (steps.length === 0) return null;
    const t = new Date(steps[0].timestamp).getTime();
    return isNaN(t) ? null : t;
  }, [steps]);
  const turnEndMs = useMemo(() => {
    if (steps.length === 0) return null;
    const t = new Date(steps[steps.length - 1].timestamp).getTime();
    return isNaN(t) ? null : t;
  }, [steps]);
  const turnElapsedMs = useMemo(() => {
    if (turnStartMs == null) return null;
    const end = isLive ? nowMs : (turnEndMs ?? nowMs);
    return Math.max(0, end - turnStartMs);
  }, [turnStartMs, turnEndMs, nowMs, isLive]);
  const turnStartedAtLabel = turnStartMs != null ? formatClockTime(steps[0].timestamp) : null;

  const expandableIndices = useMemo(() => {
    const ids: number[] = [];
    steps.forEach((step, i) => {
      if (hasMeaningfulDetails(step)) ids.push(i);
    });
    return ids;
  }, [steps]);

  const allExpanded = expandableIndices.length > 0 && expandableIndices.every((i) => expanded.has(i));

  function toggleAllExpanded() {
    if (allExpanded) {
      setExpanded(new Set());
    } else {
      setExpanded(new Set(expandableIndices));
    }
  }

  function toggleStep(i: number) {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(i)) next.delete(i); else next.add(i);
      return next;
    });
  }

  if (steps.length === 0) return null;

  const groups = groupByIteration(steps);
  const lastStepIndex = steps.length - 1;
  const lastStepReasoningChannel = typeof steps[lastStepIndex].data?.reasoning_channel === 'string'
    ? (steps[lastStepIndex].data!.reasoning_channel as string)
    : null;

  return (
    <div className={`pipeline-progress ${isLive ? 'is-live' : 'is-persisted'}`}>
      <div className="pipeline-header">
        <div className="pipeline-summary">
          {isLive && <span className="pipeline-live-pulse" aria-hidden="true" />}
          <span className="pipeline-headline">{headline}</span>
          {turnStartedAtLabel && (
            <span className="pipeline-turn-started" title={`Turn started at ${turnStartedAtLabel}`}>
              started {turnStartedAtLabel}
            </span>
          )}
          {turnElapsedMs != null && (
            <span className={`pipeline-turn-elapsed${isLive ? ' pipeline-turn-elapsed-running' : ''}`}>
              {isLive ? '⏱ ' : 'took '}{formatDuration(turnElapsedMs)}
            </span>
          )}
        </div>
        <div className="pipeline-actions">
          {showTimeline && expandableIndices.length > 0 && (
            <button
              className="pipeline-action-btn"
              type="button"
              onClick={toggleAllExpanded}
            >
              {allExpanded ? 'Collapse all' : 'Expand all'}
            </button>
          )}
          <button
            className="pipeline-toggle-btn"
            type="button"
            onClick={() => setShowTimeline((v) => !v)}
          >
            {showTimeline ? 'Hide timeline' : 'Show timeline'}
          </button>
        </div>
      </div>

      {/* Promoted artifact cards — visible without expanding the timeline */}
      {planStep && <DesignPlanCard data={planStep.data} />}
      {critiqueStep && <VisionCritiqueCard data={critiqueStep.data} />}

      {showTimeline && (
        <div className="pipeline-timeline">
          {groups.map((group, gi) => {
            const isPre = group.iteration === null;
            return (
              <div key={`g-${gi}`} className="pipeline-iteration-group">
                {!isPre && (
                  <div className="pipeline-iteration-header">
                    <span className="pipeline-iteration-badge">Iteration {group.iteration}</span>
                  </div>
                )}
                {group.steps.map((step, si) => {
                  const globalIndex = group.startIndex + si;
                  const nextStep = globalIndex < steps.length - 1 ? steps[globalIndex + 1] : undefined;
                  const isLastOverall = globalIndex === lastStepIndex;
                  const isActive = isLive && isLastOverall;
                  const channel = typeof step.data?.reasoning_channel === 'string'
                    ? (step.data!.reasoning_channel as string) : null;
                  const reasoningForStep = (isActive && channel && channel === lastStepReasoningChannel)
                    ? streamingReasoning
                    : undefined;
                  return (
                    <PipelineStepRow
                      key={`s-${globalIndex}`}
                      step={step}
                      nextStep={nextStep}
                      turnStartMs={turnStartMs}
                      nowMs={nowMs}
                      isLast={isLastOverall}
                      isExpanded={expanded.has(globalIndex)}
                      isActive={isActive}
                      reasoningText={reasoningForStep}
                      onToggle={() => toggleStep(globalIndex)}
                    />
                  );
                })}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
